### ISSUE TITLE
<form> tags shrunk widths of form field/btn

### ISSUE THREAD

**Issue by dudejeff** [slicecapital/slicedcapital.github.io#3]

**Comment by danstepanov** [comment]
@dudejeff can you please attach images of expected vs current behavior

**Comment by dudejeff** [comment]
![image](https://cloud.githubusercontent.com/assets/18409085/23072556/1a42c29e-f500-11e6-83f9-1ae03a3931c6.png)

Expected

**Comment by dudejeff** [comment]
![image](https://cloud.githubusercontent.com/assets/18409085/23072585/2ba89130-f500-11e6-9145-d49306da931f.png)

Current
