### ISSUE TITLE
Font of logo

### ISSUE THREAD

**Issue by raevskym** [slicecapital/slicedcapital.github.io#7]
unsure if intentional but "Slice Capital" looks like it's written in times new roman / not the same font as the rest of the page. looking at it on Ubuntu OS

**Comment by rohanyshah** [comment]
^I agree - not a huge fan

**Comment by danstepanov** [comment]
this is indeed an error and will be resolved

**Comment by dudejeff** [comment]
I'll just replace wiht a PNG

**Comment by danstepanov** [comment]
@dudejeff I'd be careful with this, make sure it resizes properly on mobile and that the quality is relatively lossless

**Comment by danstepanov** [comment]
The issue seems to be solved via an svg outline
